export const profileFields: FormField[] = [
  {
    name: "fullName",
    label: "Full name",
    placeholder: "Enter your full name",
    required: true,
    type: "input",
    size: { md: 6 },
  },
  {
    name: "username",
    label: "User name",
    placeholder: "Enter your user name",
    type: "input",
    disabled: true,
    size: { md: 6 },
  },
  {
    name: "email",
    label: "Email",
    placeholder: "",
    required: true,
    disabled: true,
    type: "input",
    size: { md: 6 },
  },

  {
    menuItems: ["Male", "Female", "Other"],
    disabled: true,
    name: "gender",
    label: "Gender",
    type: "select",
    required: true,
    size: { md: 6 },
  },
  {
    name: "dateOfBirth",
    label: "Date of birth",
    type: "date",
    size: { md: 6 },
  },
  {
    name: "phone",
    label: "Phone",
    placeholder: "Enter your phone",
    type: "input",
    size: { md: 6 },
  },
  {
    type: "children",
    children: [
      {
        name: "address.number",
        label: "Number address",
        placeholder: "Enter your number",
        type: "input",
        size: { md: 4 },
      },
      {
        name: "address.street",
        label: "Street address",
        placeholder: "Enter street address",
        type: "input",
        size: { md: 4 },
      },
      {
        name: "address.ward",
        label: "Ward address",
        placeholder: "Enter ward address",
        type: "input",
        size: { md: 4 },
      },
      {
        name: "address.district",
        label: "District address",
        placeholder: "Enter district address",
        type: "input",
        size: { md: 6 },
      },
      {
        name: "address.city",
        label: "City address",
        placeholder: "Enter city address",
        type: "input",
        size: { md: 6 },
      },
    ],
  },
  {
    name: "group",
    label: "Role",
    placeholder: "",
    disabled: true,
    type: "input",
    size: { md: 6 },
  },
  {
    disabled: true,
    name: "createdDate",
    label: "Created date",
    type: "date",
    size: { md: 6 },
  },
];
