export const updateEmployeeField: FormField[] = [
  {
    name: "fullName",
    label: "Full name",
    placeholder: "Enter fullName",
    icon: "carbon:email",
    type: "input",
    size: { md: 6 },
  },
  {
    name: "email",
    label: "Email",
    placeholder: "Enter email",
    icon: "carbon:email",
    type: "input",
    size: { md: 6 },
  },
  {
    menuItems: ["Male", "Female", "Other"],
    name: "gender",
    label: "Gender",
    type: "select",
    required: true,
    size: { md: 6 },
  },
  {
    name: "dateOfBirth",
    label: "Date of birth",
    type: "date",
    icon: "material-symbols:person-outline-rounded",
    size: { md: 6 },
  },
  {
    type: "children",
    children: [
      {
        name: "address.number",
        label: "Number",
        placeholder: "Enter your number",
        icon: "fluent:location-16-regular",
        type: "input",
        size: { md: 6 },
      },

      {
        name: "address.street",
        label: "Street address",
        placeholder: "Enter street address",
        icon: "fluent:location-16-regular",
        type: "input",
        size: { md: 6 },
      },
      {
        name: "address.ward",
        label: "Ward address",
        placeholder: "Enter ward address",
        icon: "fluent:location-16-regular",
        type: "input",
        size: { md: 6 },
      },
      {
        name: "address.district",
        label: "District address",
        placeholder: "Enter district address",
        icon: "fluent:location-16-regular",
        type: "input",
        size: { md: 6 },
      },
      {
        name: "address.city",
        label: "City address",
        placeholder: "Enter city address",
        icon: "fluent:city-24-regular",
        type: "input",
        size: { md: 6 },
      },
    ],
  },
];
